<?php

namespace Test\FrontBundle\Entity\Repository;

/**
 * SheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        $qb = $this->createQueryBuilder('s');
        $query=$qb;
           /* ->where('s.type= :type')
            ->setParameter('type','audio')
        ;*/

        $resultat = $query->getQuery()->execute();
        return $resultat;
    }
}
